version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source With Bun...
      - npm install -g yarn
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn run build
  post_build:
    commands:
      # copy the contents of /dist to S3
      - aws s3 cp --recursive --acl public-read ./dist s3://time-source/

      # set the cache-control headers for index.html to prevent
      # browser caching
      - >
        aws s3 cp --acl public-read
        --cache-control="max-age=0, no-cache, no-store, must-revalidate"
        ./dist/index.html s3://time-source/
artifacts:
  files:
    - '**/*'
  base-directory: dist
